project:
  type: book
  output-dir: "docs"

website:
  favicon: "img/logos/favicon.ico"
  reader-mode: true
  comments: 
    hypothesis:
      theme: clean
      openSidebar: true

book:
  title: "Physiotherapy Statistics Exams"
  author: "Alfredo Sánchez Alberca"
  date: "1/11/2022"
  output-file: "physiotheraphy-statistics-exams"
  image: img/logos/sticker.png
  cover-image: img/logos/sticker.png
  sharing: [twitter, linkedin]
  downloads: [pdf, epub]
  favicon: "img/logos/favicon.ico"
  sidebar: 
    logo: img/logos/aprendeconalf.png
    tools:
      - icon: house-fill
        href: https://aprendeconalf.es
  open-graph: true
  twitter-card: 
    site: "@aprendeconalf"
  chapters:
    - index.qmd
    # - exam-2016-04-01.qmd
    # - exam-2016-05-13.qmd
    # - exam-2016-05-19.qmd
    # - exam-2016-06-23.qmd
    - exam-2018-05-31.qmd
    - exam-2022-05-06-prob.qmd
    - exam-2022-06-06-des.qmd
    - exam-2022-06-06-prob.qmd
    - exam-2023-03-23-des.qmd

format:
  html:
    highlight-style: a11y
    theme:
      dark: darkly
      light: flatly
    html-math-method: mathjax
  pdf:
    documentclass: scrreport
    papersize: a4
    template-partials:
      - before-body.tex
    titlegraphic: img/logos/sticker.png
    institution: CEU San Pablo
    email: asalber@ceu.es
    web: https://aprendeconalf.es
    logo: img/logos/aprendeconalf.png
    include-in-header:
      - preamble.tex
      - macros.tex
    keep-tex: true
    #mainfont: TeX Gyre Termes
    #mainfontoptions:
    #  - Numbers=Lowercase
    #  - Numbers=Proportional    
    
  epub:
    cover-image: img/logos/sticker.png
